### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [andmccall/Draw3DROI#1]
Hi @andmccall ,

that's a fantastic new Fiji plugin! Great that you are sharing it open source! I was just wondering under which conditions one could [re]use the code provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blog post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by andmccall** [comment]
Right you are, just forgot to copy it over from my other plugin. Should be up there now, and thanks for letting me know.

**Comment by andmccall** [comment]
Right you are, just forgot to copy it over from my other plugin. Should be up there now, and thanks for letting me know.
